### PR TITLE
Feature/wb 102 - Email html templates

### PR DESCRIPTION
**Pull request by Yordi23**
**Changes**
- Created a new implementation for email handling, which also support HTML templates instead of just plain text.
- Updated email handling on `forgotPassword`, `emailValidation`, and `memberInvitation` endpoints.
- Added `EmailValidation`, `PasswordReset`, and `MemberIntitation` email HTML templates.

### CODE REVIEW

**Review by dreinix — APPROVED** [review]
👌

**Comment by Yordi23** [comment]
> 👌, and remove the commented block.

In which file?

**Comment by dreinix** [comment]
> > 👌, and remove the commented block.
> 
> In which file? @dreinix

EmailValidation.html

**Comment by Yordi23** [comment]
> > > 👌, and remove the commented block.
> > 
> > 
> > In which file? @dreinix
> 
> EmailValidation.html

Oh okay. I didn't make the template, but I'll fix it.

**Review by dreinix — APPROVED** [review]

**Pull request merged**
